### ISSUE TITLE
Name not shown in node

### ISSUE THREAD

**Issue by minedaddy** [stefanobertini/node-red-contrib-timegate#6]
Hello Stefano,

Changing the "Name" in the properties pane doesn't change the name displayed for the node on the workspace, which always shows "TimeGate". It would be valuable to be able to distinguish between multiple TimeGate nodes.

This is a very useful node for me. Thank you.

**Comment by stefanobertini** [comment]
My fault... just released version 1.0.5 with the fix !

**Comment by stefanobertini** [comment]
Don't forget to rate the node on NodeRed ;-)

https://flows.nodered.org/node/@stefanobertini/node-red-contrib-timegate
