### ISSUE TITLE
Variable target date feature request

### ISSUE THREAD

**Issue by minedaddy** [stefanobertini/node-red-contrib-timegate#7]
I would like to use your TimeGate to identify upcoming special dates. Right now the TimeGate compares on the current date but It would be great if I could pass a target date to know if anything is scheduled for tomorrow, as an example. Suggested logic is that the node operates as it is unless the incomming message contains a field (maybe called msg.targetDate) which is then used for all the date/time comparisons. Would this fit into your vision for TimeGate without over complicating it? 

Thanks!

**Comment by stefanobertini** [comment]
I'm not sure I got your point.

You would like to be able to have a "date" criteria that could let you configura, for example, from jan 15th to march 21st ?

**Comment by minedaddy** [comment]
I would like to know if there will be a recycling collection tomorrow and what type. (e.g. trash every Monday, leaves and branches every ODD Friday, etc.) I will setup the criteria for the whole year and for all scheduled collections using TimeGate but would like to know today, for example, what Friday's pickup will be. I'd like to supply the comparison date, in this case Fridays's date, overriding the default use of todays' date in TimeGate. The output would pass my messages through if there is a criteria matching Friday's date and I will display the result. I have tested this by modifying your code replacing:

var now = moment();
if (unittest_time) {
now = moment(unittest_time, "YYYY/MM/DD hh:mm");
}

in timegate.js with:

var now=moment(msg.targetDate, "YYYY/MM/DD hh:mm");

This doesn't check for the presence of the incomming field in msg. It is a rough test. I can inject 2023/06/23 as msg.targetDate and the node evaluates the conditions for next Friday indicating green material collection. Note - I've configured the time criteria in TimeGate as 00:00 - 23:59 to disregard the time component. There may be a benefit to some to test the time also. Perhaps if the time is considered if passed in and ignored if only a date is supplied in msg.targetTime but I hesitate to overcomplicate a node that is already solving a problem elegantly.

**Comment by stefanobertini** [comment]
Just released 1.0.6 with the new functionality.
I thought it could be better to leave the possibilty to decide where to get the reference datetime from: a msg variable, a flow variable or a global variable.

Let me know if it's ok

**Comment by minedaddy** [comment]
Great idea accepting Global and Flow input! I tested with msg, global and flow and your node works perfectly in all cases. Your updated documentation states that if the msg/flow/global variable is not set the current time will be used. I cannot clear the variable portion of the config field (shows error with red border) when I delete the default targetDateTime field name. Does this mean that I should simply not define targetDateTime in msg, global and flow to use the current time?

**Comment by stefanobertini** [comment]
Yes, to use the current date and time, just not set the targetDateTime field.

Unluckily, using a [typedInput](https://nodered.org/docs/api/ui/typedInput) field, there is no way to leave it blank. Or, at least, I didn't find it :-)

However, this is the way that many other nodes use. I think it should be ok.
